---
# environment Name
env_name: oah-health-vm
# `vagrant_box` .
vagrant_box: virtualenv/ubuntu1404
vagrant_user: vagrant
oah_user: oahdev

# If you need to run multiple instances of Openhack VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: oah-health-vm.dev
vagrant_machine_name: oah-health-vm
#vagrant_ip: 192.168.88.88
vagrant_ip: 0.0.0.0

# Allow OAH VM to be accessed via a public network interface on your host.
# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""

# A list of synced folders, with the keys 'local_path', 'destination', 'id', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares).
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_makefile: is 'true'.
  - local_path: ~/.oah/data
    destination: /home/{{ oah_user }}/.oah/data
    type: nfs
    create: true

  - local_path: ~/oah-sites/{{ vagrant_machine_name }}
    destination: /var/www/{{ vagrant_machine_name }}
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 2

# The web server software to use. Can be either 'apache' or 'nginx'.
oahvm_webserver: apache



#

# Cron jobs are added to the root user's crontab. Keys include name (required),
# minute, hour, day, weekday, month, job (required), and state.
oahvm_cron_jobs: []
  # - {
  #   name: "Drupal Cron",
  #   minute: "*/30",
  #   job: "drush -r {{ drupal_core_path }} core-cron"
  # }


# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
# View the virtualenv.apache Ansible Role README for more options.
apache_vhosts:


  - servername: "adminer.{{ vagrant_machine_name }}.dev"
    documentroot: "/opt/adminer"

  - servername: "xhprof.{{ vagrant_machine_name }}.dev"
    documentroot: "/usr/share/php/xhprof_html"

  - servername: "pimpmylog.{{ vagrant_machine_name }}.dev"
    documentroot: "/usr/share/php/pimpmylog"

apache_remove_default_vhost: true
apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load

# Nginx hosts. Each site will get a server entry using the configuration defined
# here. Set the 'is_php' property for document roots that contain PHP apps like
# Drupal.
nginx_hosts:
  - server_name: "adminer.{{ vagrant_machine_name }}.dev"
    root: "/opt/adminer"
    is_php: true

  - server_name: "xhprof.{{ vagrant_machine_name }}.dev"
    root: "/usr/share/php/xhprof_html"
    is_php: true

  - server_name: "pimpmylog.{{ vagrant_machine_name }}.dev"
    root: "/usr/share/php/pimpmylog"
    is_php: true

nginx_remove_default_vhost: true


# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  - mailhog
  - memcached
  - nodejs
  - pimpmylog
  # - ruby
  # - selenium
  # - solr
  - varnish
  - xdebug
  - xhprof

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - unzip

# `nodejs` must be in installed_extras for this to work.
nodejs_version: "0.12"
nodejs_npm_global_packages: []

# `ruby` must be in installed_extras for this to work.
ruby_install_gems: []

# You can configure almost anything else on the server in the rest of this file.
extra_security_enabled: false


firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "4200"

firewall_log_dropped_packets: false

# PHP Configuration. Currently-supported versions: 5.5, 5.6, 7.0 (experimental).
php_version: "5.6"
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_enable_php_fpm: 1
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

composer_path: /usr/bin/composer
composer_home_path: '/home/{{ oah_user }}/.composer'
# composer_global_packages:
#   - { name: phpunit/phpunit, release: '@stable' }

# MySQL Configuration.
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# Varnish Configuration.
varnish_listen_port: "81"
varnish_default_vcl_template_path: templates/oahvm.vcl.j2
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "80"

# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true

# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: sublime.xdebug
php_xdebug_max_nesting_level: 256

# Solr Configuration (if enabled above).
solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium configuration.
selenium_version: 2.46.0

# Other configuration.
known_hosts_path: ~/.ssh/known_hosts
